org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.vfs.watch=false

kotlin.code.style=official

systemProp.https.protocols=TLSv1.2,TLSv1.3
systemProp.com.sun.net.ssl.checkRevocation=false
systemProp.org.gradle.internal.http.sslRetry=false
android.useAndroidX=true
android.enableJetifier=true

kotlin.incremental=false